sudo: false
language: "python"
cache: "pip"
before_install:
    - "nvm install node && nvm use node"
    - "node --version"
    - "npm install -g dredd --no-optional"
    - "pip install -r requirements.txt"
python:
    - "3.6"
script:
    - "dredd"
