FORMAT: 1A
HOST: http://deoraclize.herokuapp.com

# Deoraclize API

## Search [GET /search{?term}]

+ Parameters
    + term: OPC (required, string) - The acronym/abbreviation you want to lookup

+ Response 200 (application/json)
    + Attributes
        + count (number) - Count of the search results
        + results (array)
            + abbr (string) - Abbreviation matching the search term
            + title (string) - Meaning of the abbreviation
            + description (string) - Detailed description
            + url (string) - URL to the source of the information
