FORMAT: 1A
HOST: http://deoraclize.herokuapp.com

# Deoraclize API

API which provides you with explanations of abbreviations and acronyms used in Oracle.

## Search [GET /search{?q}]

+ Parameters
    + q: OPC (required, string) - The acronym/abbreviation you want to lookup

+ Response 200 (application/json)
    + Attributes
        + count (number, required) - Count of the search results
        + results (array, required, fixed-type)
            + (object)
                + abbr (string, required) - Abbreviation matching the search term
                + title (string, required) - Meaning of the abbreviation
                + description (string) - Detailed description
                + url (string, required) - URL to the source of the information
